INSERT INTO BOOK_STATUS (BOOK_STATUS_CODE, BOOK_STATUS_DESCRIPTION) VALUES ('A', 'Available');
INSERT INTO BOOK_STATUS (BOOK_STATUS_CODE, BOOK_STATUS_DESCRIPTION) VALUES ('D', 'Deleted');
INSERT INTO BOOK_STATUS (BOOK_STATUS_CODE, BOOK_STATUS_DESCRIPTION) VALUES ('T', 'Temporarily Unavailable');

INSERT INTO BOOK_LANGUAGE (LANG_CODE, LANG_NAME) VALUES ('EN', 'ENGLISH');
INSERT INTO BOOK_LANGUAGE (LANG_CODE, LANG_NAME) VALUES ('BN', 'BENGALI');
INSERT INTO BOOK_LANGUAGE (LANG_CODE, LANG_NAME) VALUES ('HI', 'HINDI');

INSERT INTO BOOK_GENRE (GENRE_CODE, DESCRIPTION) VALUES ('FNTY', 'FANTASY');
INSERT INTO BOOK_GENRE (GENRE_CODE, DESCRIPTION) VALUES ('SCFI', 'SCIENCE_FICTION');
INSERT INTO BOOK_GENRE (GENRE_CODE, DESCRIPTION) VALUES ('WSTR', 'WESTERN');
INSERT INTO BOOK_GENRE (GENRE_CODE, DESCRIPTION) VALUES ('ROMN', 'ROMANCE');
INSERT INTO BOOK_GENRE (GENRE_CODE, DESCRIPTION) VALUES ('THRL', 'THRILLER');
INSERT INTO BOOK_GENRE (GENRE_CODE, DESCRIPTION) VALUES ('MYST', 'MYSTERY');
INSERT INTO BOOK_GENRE (GENRE_CODE, DESCRIPTION) VALUES ('DETC', 'DETECTIVE_STORY');
